{{- if (
  and
    (eq .Values.global.authentication.provider "azure")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.azure.clientSecret.secretRef)
      (empty .Values.global.airflow.openmetadata.authConfig.azure.clientSecret.secretKey)
      (empty .Values.global.airflow.openmetadata.authConfig.azure.authority)
      (empty .Values.global.airflow.openmetadata.authConfig.azure.clientId )
      (empty .Values.global.airflow.openmetadata.authConfig.azure.scopes)
    )
) }}
  {{ required "The authentication provider azure must be configured in .global.airflow.openmetadata.authConfig.azure" nil }}
{{- end }}

{{- if (
  and
    (eq .Values.global.authentication.provider "google")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.google.secretKeyPath)
      (empty .Values.global.airflow.openmetadata.authConfig.google.audience)
    )
) }}
  {{ required "The authentication provider google must be configured in .global.airflow.openmetadata.authConfig.google" nil }}
{{- end }}

{{- if (
  and
    (eq .Values.global.authentication.provider "okta")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.okta.privateKey.secretRef)
      (empty .Values.global.airflow.openmetadata.authConfig.okta.privateKey.secretKey)
      (empty .Values.global.airflow.openmetadata.authConfig.okta.email)
      (empty .Values.global.airflow.openmetadata.authConfig.okta.clientId)
      (empty .Values.global.airflow.openmetadata.authConfig.okta.orgUrl)
      (empty .Values.global.airflow.openmetadata.authConfig.okta.scope)
    )
) }}
  {{ required "The authentication provider okta must be configured in .global.airflow.openmetadata.authConfig.okta" nil }}
{{- end }}

{{- if (
  and
    (eq .Values.global.authentication.provider "auth0")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.auth0.secretKey.sercretRef)
      (empty .Values.global.airflow.openmetadata.authConfig.auth0.secretKey.secretKey)
      (empty .Values.global.airflow.openmetadata.authConfig.auth0.domain)
      (empty .Values.global.airflow.openmetadata.authConfig.auth0.clientId)
    )
) }}
  {{ required "The authentication provider auth0 must be configured in .global.airflow.openmetadata.authConfig.auth0" nil }}
{{- end }}

{{- if (
  and
    (eq .Values.global.authentication.provider "openmetadata")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.openmetadata.jwtToken.secretRef)
      (empty .Values.global.airflow.openmetadata.authConfig.openmetadata.jwtToken.secretKey)
    )
) }}
  {{ required "The authentication provider openmetadata must be configured in .global.airflow.openmetadata.authConfig.openmetadata" nil }}
{{- end }}

{{- if (
 and
    (eq .Values.global.authentication.provider "custom-oidc")
    (.Values.global.airflow.enabled)
    (
      or
      (empty .Values.global.airflow.openmetadata.authConfig.customOidc.secretKey.sercretRef)
      (empty .Values.global.airflow.openmetadata.authConfig.customOidc.secretKey.secretKey)
      (empty .Values.global.airflow.openmetadata.authConfig.customOidc.tokenEndpoint)
      (empty .Values.global.airflow.openmetadata.authConfig.customOidc.clientId)
    )
) }}
  {{ required "The authentication provider custom-oidc must be configured in .global.airflow.openmetadata.authConfig.customOidc" nil }}
{{- end }}
